### ISSUE TITLE
Base::Configure should put -as_base to default_exports()

### ISSUE THREAD

**Issue by makamaka** [hkoba/perl-mop4import-declare#30]
T/O.

**Comment by hkoba** [comment]
Unfortunately, I found this change invites confusing result when I just wrote ```perl
use Backend;
```  in `app.psgi` ...

**Comment by hkoba** [comment]
Since `import` is **inherited** to all sub-classes of `MOP4Import::Base::Configure` families, this `always_exports()` affects not only them but also all **user** codes which just `use` -ed them. This causes catastrophic situation and is very hard to debug unless you already know this pitfall.

So, I decided not to include `-as_base` in `always_exports()` of the base class `MOP4Import::Base::Configure`.

Now we have 2 options.
1. Move the `always_exports()` down to `MOP4Import::Base::CLI_Opts` to keep the usage in this issue.
2. Remove all support for it.

Which do you like?

**Comment by hkoba** [comment]
Unfortunately (again), I found adding `-as_base` for your tests is not enough.

```
% prove -v t/102_base_cli_cmd.t
t/102_base_cli_cmd.t ..
ok 1
ok 2
ok 3
Invalid option format - --help at t/102_base_cli_cmd.t line 98.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 3.
Dubious, test returned 255 (wstat 65280, 0xff00)
All 3 subtests passed
```

It seems to me CLI_Opts relies on `default_exports()` too.

Without fixing above, our only option is `1.` (move -as_base to CLI_Opts).
